coursework2/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('register/', user_register_view, name="register"),
    path('login/', user_login_view, name="login"),
    path('logout/', user_logout_view, name="logout"),
    path('search/', user_search_view, name="search"),
    path('<user_id>/', user_view, name="user_view"),
    path('<user_id>/edit/', edit_particulars_view, name="edit"),
    path('<user_id>/edit/cropImg', crop_image_view, name="crop_image"),
]

coursework2/base/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home_screen, name='home'),
]

coursework2/coursework2/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

from accounts.views import *

urlpatterns = [
    path('', include('base.urls'), name="home"),
    path('account/', include('accounts.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('friend/', include('friends.urls', namespace='friend')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('status/', include('status.urls', namespace='status')),
    
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password/password_change.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password/password_change_done.html'), name='password_change_done'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

coursework2/friends/urls.py
from django.urls import path
from .views import *

app_name = "friends"

urlpatterns = [
    path('friend_request/', send_friend_request_view, name="friend-request"),
    path('friend_request/<user_id>', friend_requests_view, name="friend-requests"),
    path('accept_friend_request/<friend_request_id>', accept_friend_request_view, name="friend-request-accept"), 
    path('remove_friend/', remove_friend_view, name="remove-friend"),
    path('decline_friend_request/<friend_request_id>', decline_friend_request_view, name="friend-request-decline"), 
    path('cancel_friend_request/', cancel_friend_request_view, name="friend-request-cancel"),    
    path('friends_list/<user_id>', friends_list_view, name="friends-list"),    

]

coursework2/status/urls.py
from django.urls import path
from .views import *

app_name = "status"

urlpatterns = [
    path('', timeline_view, name="timeline"),
    path('<user_id>/', status_profile_view, name="status-profile"),
]

coursework2/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin

class AccountManager(BaseUserManager):
    def create_user(self, email, username, full_name, password=None):
        if not email:
            raise ValueError('An account needs an email address')
        if not username:
            raise ValueError('An account needs a username')
        if not full_name:
            raise ValueError('An account needs a name')

        email = self.normalize_email(email)    
        user = self.model(
            email = email,
            username = username,
            full_name = full_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, full_name, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            full_name = full_name,
            password=password,
        )
        
        user.is_admin=True
        user.is_staff=True
        user.is_superuser=True
        user.save(using=self._db)
        return user
        
# profile_images file will be saved in media_cdn separated by pk of user
def get_profile_image(self, filename):
    return 'profile_images/'+ str(self.pk) + '/"profile_image.png"'

def get_default_profile_image():
    return "defaultImgs/default_profile_image.jpg"


class Account(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name="email", max_length=256, unique=True)
    username = models.CharField(max_length=20, unique=True)
    full_name = models.CharField(max_length=256)
    date_of_birth = models.DateField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    profile_image = models.ImageField(max_length=256, upload_to=get_profile_image, null=True, blank=True, default=get_default_profile_image)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    hide_email = models.BooleanField(default=True)

    objects = AccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name', 'username']

    def __str__(self):
        return self.email

    # all admins will have all permissions
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # does current user have permission to view app
    def has_module_perms(self, app_label):
        return True

coursework2/accounts/views.py
import datetime
import os
import cv2 #opencv
import json
import base64
import requests

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth import login, authenticate , logout
from django.contrib import messages
from django.conf import settings
from django.core.files.storage import default_storage, FileSystemStorage
from django.core import files

from friends.models import *
from .forms import *
from .models import *
from friends.friend_request_status import *

TEMP_PROFILE_IMAGE_NAME = "temp_profile_image.png"

# Create your views here.

# Register View
def user_register_view(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        return HttpResponse("You are already authenticated as " + str(user.email))
    
    context = {}
    if request.method == 'POST':
        registration_form = RegistrationForm(request.POST)
        if registration_form.is_valid():
            # validates the data and creates the account
            print(registration_form.cleaned_data)
            registration_form.save()
            messages.success(request,'Your account has been successfully created!')
        else:
            context['registration_form'] = registration_form
    else:
        registration_form = RegistrationForm()
        context['registration_form'] = registration_form

    return render(request, 'accounts/register.html', context)

# Login View
def user_login_view(request):
    context={}

    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            
            if user:
                if user.is_active:
                    login(request,user)
                    return redirect("home")
                else:
                    return HttpResponse("Your account is disabled")
            else:
                return HttpResponse('Invalid login')
    else:
        login_form = LoginForm()
    
    context['login_form'] = login_form
    return render(request, "accounts/login.html", context)

# Logout view
def user_logout_view(request):
    logout(request)
    return redirect("home")

# Account view
def user_view(request, *args, **kwargs):
    context = {}
    user_id = kwargs.get("user_id")
    try:
        account = Account.objects.get(pk=user_id)
    except:
        return HttpResponse("Something went wrong.")
    if account:
        context['id'] = account.id
        context['full_name'] = account.full_name
        context['username'] = account.username
        context['email'] = account.email
        context['date_of_birth'] = account.date_of_birth
        context['profile_image'] = account.profile_image.url
        context['hide_email'] = account.hide_email

        try:
            # retrieve the friend list
            friends_list = FriendsList.objects.get(user=account)
        except FriendsList.DoesNotExist:
            #if friend list does not exist create one
            friends_list = FriendsList(user=account)
            friends_list.save()
        # retrieve all friends of the user
        friends = friends_list.friends.all()
        context['friends'] = friends

        # Template vars
        is_self = True
        is_friend = False
        request_sent = FriendRequestStatus.no_request.value
        friend_requests = None
        user = request.user
        if user.is_authenticated and user != account:
            is_self = False
            # search through person friend list to check for user
            if friends.filter(pk=user.id):
                is_friend = True
            else:
                is_friend = False
                # Friend send to you
                if get_friend_request(sender=account, receiver=user) != False:
                    request_sent = FriendRequestStatus.friend_sent.value
                    # retrieve the primary key
                    context['friend_request_id'] = get_friend_request(sender=account, receiver=user).pk
                # You send to friend
                elif get_friend_request(sender=user, receiver=account) != False:
                    request_sent = FriendRequestStatus.user_sent.value
                # no request
                else:
                    request_sent = FriendRequestStatus.no_request.value
        elif not user.is_authenticated:
            is_self = False
        # Looking at own account, check friend requests
        else:
            try:
                friend_requests = FriendRequest.objects.filter(receiver=user, pending_request_status=True)
            except:
                pass
        # Set the template variables to the values
        context['is_self'] = is_self
        context['is_friend'] = is_friend
        context['BASE_URL'] = settings.BASE_URL
        context['request_sent'] = request_sent
        context['friend_requests'] = friend_requests
        return render(request, "accounts/account.html", context)

# Search Friends View
def user_search_view(request, *args, **kwargs):
    context = {}

    if request.method == 'GET':
        #searching for variable q
        search_query = request.GET.get("q")
        if len(search_query) > 0:
            # filter to get multiple rows because can have more than 1 result
            search_results = Account.objects.filter(full_name__icontains=search_query).filter(
                username__icontains=search_query).filter(email__icontains=search_query).distinct()
            user = request.user
            # in array store account details and if you are friends or not
            accounts = []
            if user.is_authenticated:
                user_friend_list = FriendsList.objects.get(user=user)
                for account in search_results:
                    accounts.append((account, user_friend_list.check_mutual_friends(account)))
                context['accounts'] = accounts
            else:
                for account in search_results:
                    accounts.append((account, False))
                context['accounts'] = accounts

    return render(request, "accounts/search.html", context)

# Edit Particulars View
def edit_particulars_view(request, *args, **kwargs):
    context = {}

    # check if user is logged in
    if not request.user.is_authenticated:
        return redirect("account:login")
    user_id = kwargs.get("user_id")
    try:
        account = Account.objects.get(pk=user_id)
    except Account.DoesNotExist:
        return HttpResponse("Something went wrong")

    # check if user editing own profile    
    if account.pk != request.user.pk:
        return HttpResponse("This is not your account, you are not allowed to edit this profile!")
    
    if request.method == "POST":
        update_form = EditParticularsForm(request.POST, request.FILES, instance=request.user)
        if update_form.is_valid():
            #delete old profile image so keep the name
            account.profile_image.delete()
            update_form.save()
            return redirect("account:user_view", user_id=account.pk)
        else:
            if(account.date_of_birth == None ):
                date_time_val = account.date_of_birth
            else:
                date_time_val = datetime.datetime.strptime(str(account.date_of_birth), '%Y-%m-%d').strftime('%Y-%m-%d')

            update_form = EditParticularsForm(request.POST, instance=request.user,
                initial={
                    "id": account.pk,
                    "email": account.email,
                    "username": account.username,
                    "full_name": account.full_name,
                    "date_of_birth": date_time_val,
                    "profile_image":account.profile_image,
                    "hide_email": account.hide_email,
                }
            )
            context['update_form'] = update_form

    else:
        if(account.date_of_birth == None):
            date_time_val = account.date_of_birth
        else:
            date_time_val = datetime.datetime.strptime(str(account.date_of_birth), '%Y-%m-%d').strftime('%Y-%m-%d')
        
        update_form = EditParticularsForm(
                    initial={
                        "id": account.pk,
                        "email": account.email,
                        "username": account.username,
                        "full_name": account.full_name,
                        "date_of_birth": date_time_val,
                        "profile_image":account.profile_image,
                        "hide_email": account.hide_email,
                    }
        )

        context['update_form'] = update_form
    return render(request, "accounts/update_particulars.html", context)

def save_temp_profile_image_from_base64String(imageString, user):
    try:
        # all users have a unique temp profile image depending on primary key
        if not os.path.exists(settings.TEMP):
            os.mkdir(settings.TEMP)
        if not os.path.exists(settings.TEMP + "/" + str(user.pk)):
            os.mkdir(settings.TEMP + "/" + str(user.pk))
        url = os.path.join(settings.TEMP + "/" + str(user.pk), TEMP_PROFILE_IMAGE_NAME)
        storage = FileSystemStorage(location=url)
        image = base64.b64decode(imageString)
        with storage.open('', 'wb+') as destination:
            destination.write(image)
            destination.close()
        return url

    except Exception as e:
        if str(e) == "Incorrect padding":
            imageString += "=" * ((4 - len(imageString) % 4) % 4)
            return save_temp_profile_image_from_base64String(imageString, user)
        return None

# called asynchronously through AJAX
def crop_image_view(request, *args, **kwargs):
    payload = {}
    user = request.user
    if request.POST and user.is_authenticated:
        try:

coursework2/accounts/templates/accounts/account.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.card{
		border-radius: 12px;
	}

	.card-border-background {
		border: 3px solid black;
		background-color: white;
	}

	.image-container{
		max-width: 200px;
		height: auto;
	}

	.label-field{
		color: grey;
	}

	.friend-text{
		font-weight: bold;
		color: black;
	}

</style>

<div class="container-fluid">
	<div class="d-flex flex-row justify-content-center flex-wrap align-items-start">
		<div class="card-border-background card m-2">
			<div class="card-header">
				<h3>{{full_name}}'s Profile</h3>
			</div>
			<div class="card-body">
				<div class="flex-column justify-content-center p-4">
					<div class="image-container mx-auto mb-4">
						<img class="rounded-circle img-fluid mx-auto profile-image" alt="default image logo" id="id_profile_image" src="{{profile_image}}">
					</div>

					<p class="mb-2 label-field font-italic">Email Address</p>
					{%  if is_self %}
						<p class="font-weight-bold">{{email}}</p>
					{% else %}
						{% if hide_email %}
							<p class="font-weight-bold">User decided to make their email address private</p>
						{% else %}
							<h5>{{email}}</h5>
						{% endif %}
					{% endif %}

					<p class="mb-2 label-field font-italic">Full Name</p>
					<p class="font-weight-bold">{{full_name}}</p>

					<p class="mb-2 label-field font-italic">Username</p>
					<p class="font-weight-bold">{{username}}</p>

					<p class="mb-2 label-field font-italic">Date of Birth</p>
					<p class="font-weight-bold">{{date_of_birth}}</p>

					<!-- If user is viewing their own profile -->
					{% if is_self %}
						<!-- user_id = id, id is gotten from user_view -->
						<a  class="mt-4 btn btn-dark btn-block" href="{% url 'account:edit' user_id=id %}">Update</a>
						<div class="d-flex flex-column mt-4">
							<a class="m-auto" href="{% url 'password_change' %}">Change password</a>
						</div>
					{% endif %}
				</div>
			</div>
		</div>

		<!-- For sending, cancel and removing friend  -->
		{% if request.user.is_authenticated %}
			<div class="d-flex flex-column mb-4">
				<div class="card-border-background card m-2 px-4 pb-4">
					{% if is_friend == False and is_self == False %}
						<!-- You send friend request -->
						{% if request_sent == 1 %}
						<div class="d-flex pt-3 align-items-center">
							<button class="btn btn-danger" id="id_cancel_friend_request_btn">
								Cancel Friend Request
							</button>
						</div>
						{% endif %}

						<!-- Default view with no requests -->
						{% if request_sent == 0 %}
						<div class="d-flex pt-3 align-items-center ">
							<button class="btn btn-dark" id="id_send_friend_request_btn">
								Send Friend Request
							</button>
						</div>
						{% endif %}
					{% endif %}

					<!-- If already friends -->
					{% if is_friend %}
					<div class="d-flex pt-4 align-items-center ">
						<p class="font-weight-bold">You're Already Friends</p>
					</div>
					{% endif %}
					
					<!-- Friends list link -->
					<div class="d-flex flex-column pt-4">
						<a href="{% url 'friend:friends-list' user_id=id %}">
							<div class="d-flex flex-row align-items-center justify-content-center">
								<span class="friend-text">Friend(s) [{{friends|length}}]</span>
							</div>
						</a>
					</div>
				</div>

				<!-- Remove Friend -->
				{% if is_friend %}
				<div class="d-flex flex-column mb-4">
					<div class="card m-2 px-4 pb-4">
						<div class="d-flex pt-3 align-items-center">
							<button class="btn btn-danger" id="id_unfriend_btn" onclick="removeFriend('{{id}}', onFriendRemoved)">
								Remove Friend
							</button>
						</div>
					</div>
				</div>
				{% endif %}

				
				{% if is_self or is_friend %}
				<!-- View status of user page -->
				<div class="card m-2 px-4 pb-4">
					<div class="d-flex flex-column pt-4">
						<a href="{% url 'status:status-profile' user_id=id %}">
							<div class="d-flex flex-row align-items-center justify-content-center">
								<span class="friend-text">View Statuses</span>
							</div>
						</a>
					</div>
				{% endif %}

				<!-- Friend Requests -->
				{% if friend_requests %}
				<div class="card m-2 px-4 pb-4">
					<div class="d-flex flex-column pt-4">
						<a href="{% url 'friend:friend-requests' user_id=id %}">
							<div class="d-flex flex-row align-items-center justify-content-center">
								<span class="friend-text">Friend Requests ({{friend_requests|length}})</span>
							</div>
						</a>
					</div>
				</div>
				{% endif %}

				<!-- Friend Requests -->
				{% if is_friend %}

				{% endif %}

			</div>
		{% endif %}
	</div>
</div>

<script type="text/javascript">

	function onFriendRequestSent(){
		location.reload();
	}

	function onFriendRequestCancelled(){
		location.reload();
	}

	function onFriendRemoved(){
		location.reload();
	}

	var sendFriendRequestBtn = document.getElementById("id_send_friend_request_btn")
	if (sendFriendRequestBtn != null){
		sendFriendRequestBtn.addEventListener("click", function(){
			// sendFriendRequest ajax, takes id for profile looking at, and then reload page
			sendFriendRequest("{{id}}", onFriendRequestSent)
		})
	}

	var cancelFriendRequestBtn = document.getElementById("id_cancel_friend_request_btn")
	if(cancelFriendRequestBtn != null){
		cancelFriendRequestBtn.addEventListener("click", function(){
			cancelFriendRequest("{{id}}", onFriendRequestCancelled)
		})
	}

	var removeFriendBtn = document.getElementById("id_unfriend_btn")
	if (removeFriendBtn != null){
		removeFriendBtn.addEventListener("click", function(){
			removeFriend("{{id}}", onFriendRemoved)
		})
	}
	
</script>

{% include 'friends/ajaxScript/send_friend_request.html' %}
{% include 'friends/ajaxScript/cancel_friend_request.html' %}
{% include 'friends/ajaxScript/remove_friend.html' %}

{% endblock content %}

coursework2/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
  .signin {
	border: 3px solid black;
	background-color: white;
	width: 100%;
	max-width: 400px;
	padding: 15px;
	margin: auto;
  }

  .form-signin input{
    margin-bottom: 20px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
</style>

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="signin rounded">
		  <div class="card-header">
			<h3>Login</h3>
		  </div>
		  <div class="card-body">
		    <form class="form-signin" method="post">
				{% csrf_token %}

				<label for="inputEmail">Email Address</label>
				<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

				<label for="inputPassword">Password</label>
				<input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

				{% for field in login_form %}
					{% for error in field.errors %}
						<p style="color: salmon">{{ error }}</p>
					{% endfor %}
				{% endfor %}

				{% if login_form.non_field_errors %}
					<div style="color: salmon">
						<p>{{login_form.non_field_errors}}</p>
					</div>
				{% endif %}

				<button class="btn btn-dark btn-block" type="submit">Log in</button>
			</form>

				<div class="d-flex flex-column my-4">
					<a class="m-auto" href="{% url 'password_reset' %}">Forgotten your pasword?</a>
				</div>
		  </div>
		</div>
		
	</div>
</div>

{% endblock content %}

coursework2/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
  .signup {
	  border: 3px solid black;
	  background-color: white;
	  width: 100%;
	  max-width: 400px;
	  padding: 15px;
	  margin: auto;
  }
  
  .form-signup input{
    margin-bottom: 20px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
</style>

<div class="container">
	<div class="row justify-content-center">
		<div class="signup rounded">
			<div class="card-header">
				<h3>Register</h3>
				<p>Quick and easy</p>
			</div>
			<div class="card-body">
		    <form class="form-signup" method="POST">
                {% csrf_token %}
				<label for="inputName">Full Name</label>
                <input type="text" name="full_name" id="inputName" class="form-control" placeholder="Enter full name" required autofocus>

				<label for="inputEmail">Email Address</label>
				<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Enter email" required>

				<label for="inputUsername">Username</label>
				<input type="text" name="username" id="inputUsername" class="form-control" placeholder="Enter username" required>

				<label for="inputPassword1">Password</label>
				<input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

				<label for="inputPassword2">Confirm Password</label>
				<input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm password" required>

				<label for="inputDOB">Date Of Birth</label>
                <input type="date" name="date_of_birth" id="inputDOB" class="form-control">

				{% for field in registration_form %}
					<p>
					{% for error in field.errors %}
					<p style="color: salmon">{{ error }}</p>
				{% endfor %}
				</p>
				{% endfor %}
				{% if registration_form.non_field_errors %}
					<div style="color: salmon">
						<p>{{registration_form.non_field_errors}}</p>
					</div>
				{% endif %}

				{% if messages %}
				<ul class="messages">
					{% for message in messages %}
					<div style="color:green">
						<p>{{ message }}</p>
					</div>
					{% endfor %}
				</ul>
				{% endif %}
				
				<button class="btn btn-dark btn-block" type="submit">Register</button>

			</form>
		  </div>
		</div>
		
	</div>
</div>

{% endblock content %}

coursework2/accounts/templates/accounts/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.checkmark-icon{
		color: green;
	}
	.cancel-icon{
		color: red;
	}
</style>

<div class="container">
	<div class="card p-2">

		{% if accounts %}
		<div class="d-flex flex-row flex-wrap">
		{% for account in accounts %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<a class="profile-link" href="{% url 'account:user_view' user_id=account.0.id %}">
				<div class="card-image m-2">
					<img class="img-fluid profile-image" src="{{account.0.profile_image.url}}" alt="">
				</div>
			</a>
			<a class="profile-link" href="{% url 'account:user_view' user_id=account.0.id %}">
				<div class="card-center px-2">
					<h4 class="card-title">{{account.0.username}}</h4>
				</div>
			</a>
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
				{% if request.user.is_authenticated %}
					{% if account.1 %}
						<div class="d-flex flex-row friends-text-container p-3">
							<p class="friends-text m-auto">
								Friends 
							</p>
							<span class="material-icons checkmark-icon m-auto pl-2">
							check_circle_outline
							</span>
						</div>
					{% else %}
						{% if account.0 !=  request.user %}
							<div class="d-flex flex-row friends-text-container p-3">
								<p class="friends-text m-auto">
									Not Friends 
								</p>
								<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
							</div>
						{% endif %}
					{% endif %}
				{% endif %}
				{% if account.0 == request.user %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							This is you 
						</p>
						<span class="material-icons m-auto pl-2">
						person_pin
						</span>
					</div>
				{% endif %}
			</div>
		</div>
		{% if forloop.counter|divisibleby:2 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}
		
		{% endfor %}
		
		{% else %}
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No results</p>
		</div>
		{% endif %}
		</div>
	</div>
</div>

{% endblock content %}

coursework2/accounts/templates/accounts/update_particulars.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<style type="text/css">
	.image-container{
		max-width: 250px;
		height: auto;
		position: relative;
	}

	.card-border-background {
		border: 3px solid black;
		background-color: white;
	}

	.label-field{
		color: grey;
	}

	#id_confirm{
		color: green;
	}

	#id_confirm:hover {
		opacity: 0.2;
	}

	#id_cancel:hover {
		opacity: 0.2;
	}

	#id_cancel{
		color: salmon;
	}

	.material-icons{
		font-size: 34px;
	}

</style>

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card card-border-background">
			<div class="card-body">
				<div class="d-flex flex-column justify-content-center p-4">
					<div class="image-container" id="id_image_container">
						<img class="border border-dark rounded-circle img-fluid mx-auto profile-image" id="id_profile_image_display" src="{{update_form.initial.profile_image.url}}" alt="defaultprofile img">
						<div class="middle" id="id_middle_container">
							<div class="text" id="id_text">Edit</div>
						</div>
					</div>

					<form class="form-signup" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						
						<!-- profile image -->
						<input class="d-none" type="file" id="id_profile_image" name="profile_image" onchange="readURL(this)">
						
						<p class="mt-3 label-field font-italic">Email Address</p>
						<input type="email" name="email" id="id_input_email" class="form-control" placeholder="Email address" required autofocus value={{update_form.initial.email}}>
						
						<p class="mt-3 label-field font-italic">Full Name</p>
						<input type="text" name="full_name" id="id_input_full_name" class="form-control" placeholder="Full name" required
						value="{{update_form.initial.full_name}}">
						
						<p class="mt-3 label-field font-italic">Username</p>
						<input type="text" name="username" id="id_input_username" class="form-control" placeholder="Username" required
						value="{{update_form.initial.username}}">
						
						<p class="mt-3 label-field font-italic">Date Of Birth</p>
						<input type="date" name="date_of_birth" id="id_input_date_of_birth" class="form-control"
						value="{{update_form.initial.date_of_birth}}">
						
						<div class="mt-3 checkbox">
							<label>
								<input type="checkbox" name="hide_email" id="id_input_hide_email" {% if update_form.initial.hide_email %}checked{%endif%}>
								Hide Email
							</label>
						</div>

						{% for field in update_form %}
						<p>
						{% for error in field.errors %}
						<p style="color: salmon">{{ error }}</p>
						{% endfor %}
						</p>
						{% endfor %}
						{% if update_form.non_field_errors %}
						<div style="color: salmon">
						<p>{{update_form.non_field_errors}}</p>
						</div>
						{% endif %}

						<div class="d-flex flex-column mt-4">
							<button class="mt-4 btn btn-dark btn-block" type="submit">Save</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% include 'accounts/ajaxScript/editImage.html' %}

{% endblock content %}