coursework2/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('register/', user_register_view, name="register"),
    path('login/', user_login_view, name="login"),
    path('logout/', user_logout_view, name="logout"),
    path('search/', user_search_view, name="search"),
    path('<user_id>/', user_view, name="user_view"),
    path('<user_id>/edit/', edit_particulars_view, name="edit"),
    path('<user_id>/edit/cropImg', crop_image_view, name="crop_image"),
]

coursework2/base/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home_screen, name='home'),
]

coursework2/coursework2/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

from accounts.views import *

urlpatterns = [
    path('', include('base.urls'), name="home"),
    path('account/', include('accounts.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('friend/', include('friends.urls', namespace='friend')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('status/', include('status.urls', namespace='status')),
    
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password/password_change.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password/password_change_done.html'), name='password_change_done'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

coursework2/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import authenticate
from .models import *

# For Registration
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=256)

    class Meta:
        model = Account
        fields = ('username', 'email', 'full_name', 'date_of_birth' , 'password1', 'password2')

        #validation, must have clean infront for django to know.
        def clean_email(self):
            email = self.cleaned_data["email"].lower()
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
            except Account.DoesNotExist:
                return email
            raise forms.ValidationError('Email "%s" is alreade in use' % account)

        def clean_username(self):
            username = self.cleaned_data["username"]
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
            except Account.DoesNotExist:
                return username
            raise forms.ValidationError('Username "%s" is alreade in use' % username)

        def clean_password2(self):
            # Check that the two password entries match
            password1 = self.cleaned_data["password1"]
            password2 = self.cleaned_data["password2"]
            if password1 and password2 and password1 != password2:
                raise forms.ValidationError("Passwords don't match")
            return password2
        
        def save(self, commit=True):
            account = super(RegistrationForm, self).save(commit=False)
            account.email = self.cleaned_data["email"]
            if commit:
                account.save()   
            return account


# For Login
class LoginForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    
    class Meta:
        model = Account
        fields = ('email', 'password')
    
    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Not a valid login.")

# For Account Update Particulars
class EditParticularsForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('email', 'full_name', 'username', 'date_of_birth', 'profile_image', 'hide_email')

    def clean_email(self):
                email = self.cleaned_data.get("email").lower()
                try:
                    account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
                except Account.DoesNotExist:
                    return email
                raise forms.ValidationError('Email "%s" is alreade in use' % account)

    def clean_username(self):
                username = self.cleaned_data.get("username")
                try:
                    account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
                except Account.DoesNotExist:
                    return username
                raise forms.ValidationError('Username "%s" is alreade in use' % account)

    def save(self, commit=True):
        # apply database but not commiting it.
        account = super(EditParticularsForm, self).save(commit=False)    
        account.email = self.cleaned_data['email']
        account.full_name = self.cleaned_data['full_name']
        account.username = self.cleaned_data['username']
        account.date_of_birth = self.cleaned_data['date_of_birth']
        account.profile_image = self.cleaned_data['profile_image']
        account.hide_email = self.cleaned_data['hide_email']
        if commit:
            account.save()
        return account

coursework2/accounts/views.py
import datetime
import os
import cv2 #opencv
import json
import base64
import requests

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth import login, authenticate , logout
from django.contrib import messages
from django.conf import settings
from django.core.files.storage import default_storage, FileSystemStorage
from django.core import files

from friends.models import *
from .forms import *
from .models import *
from friends.friend_request_status import *

TEMP_PROFILE_IMAGE_NAME = "temp_profile_image.png"

# Create your views here.

# Register View
def user_register_view(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        return HttpResponse("You are already authenticated as " + str(user.email))
    
    context = {}
    if request.method == 'POST':
        registration_form = RegistrationForm(request.POST)
        if registration_form.is_valid():
            # validates the data and creates the account
            print(registration_form.cleaned_data)
            registration_form.save()
            messages.success(request,'Your account has been successfully created!')
        else:
            context['registration_form'] = registration_form
    else:
        registration_form = RegistrationForm()
        context['registration_form'] = registration_form

    return render(request, 'accounts/register.html', context)

# Login View
def user_login_view(request):
    context={}

    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            
            if user:
                if user.is_active:
                    login(request,user)
                    return redirect("home")
                else:
                    return HttpResponse("Your account is disabled")
            else:
                return HttpResponse('Invalid login')
    else:
        login_form = LoginForm()
    
    context['login_form'] = login_form
    return render(request, "accounts/login.html", context)

# Logout view
def user_logout_view(request):
    logout(request)
    return redirect("home")

# Account view
def user_view(request, *args, **kwargs):
    context = {}
    user_id = kwargs.get("user_id")
    try:
        account = Account.objects.get(pk=user_id)
    except:
        return HttpResponse("Something went wrong.")
    if account:
        context['id'] = account.id
        context['full_name'] = account.full_name
        context['username'] = account.username
        context['email'] = account.email
        context['date_of_birth'] = account.date_of_birth
        context['profile_image'] = account.profile_image.url
        context['hide_email'] = account.hide_email

        try:
            # retrieve the friend list
            friends_list = FriendsList.objects.get(user=account)
        except FriendsList.DoesNotExist:
            #if friend list does not exist create one
            friends_list = FriendsList(user=account)
            friends_list.save()
        # retrieve all friends of the user
        friends = friends_list.friends.all()
        context['friends'] = friends

        # Template vars
        is_self = True
        is_friend = False
        request_sent = FriendRequestStatus.no_request.value
        friend_requests = None
        user = request.user
        if user.is_authenticated and user != account:
            is_self = False
            # search through person friend list to check for user
            if friends.filter(pk=user.id):
                is_friend = True
            else:
                is_friend = False
                # Friend send to you
                if get_friend_request(sender=account, receiver=user) != False:
                    request_sent = FriendRequestStatus.friend_sent.value
                    # retrieve the primary key
                    context['friend_request_id'] = get_friend_request(sender=account, receiver=user).pk
                # You send to friend
                elif get_friend_request(sender=user, receiver=account) != False:
                    request_sent = FriendRequestStatus.user_sent.value
                # no request
                else:
                    request_sent = FriendRequestStatus.no_request.value
        elif not user.is_authenticated:
            is_self = False
        # Looking at own account, check friend requests
        else:
            try:
                friend_requests = FriendRequest.objects.filter(receiver=user, pending_request_status=True)
            except:
                pass
        # Set the template variables to the values
        context['is_self'] = is_self
        context['is_friend'] = is_friend
        context['BASE_URL'] = settings.BASE_URL
        context['request_sent'] = request_sent
        context['friend_requests'] = friend_requests
        return render(request, "accounts/account.html", context)

# Search Friends View
def user_search_view(request, *args, **kwargs):
    context = {}

    if request.method == 'GET':
        #searching for variable q
        search_query = request.GET.get("q")
        if len(search_query) > 0:
            # filter to get multiple rows because can have more than 1 result
            search_results = Account.objects.filter(full_name__icontains=search_query).filter(
                username__icontains=search_query).filter(email__icontains=search_query).distinct()
            user = request.user
            # in array store account details and if you are friends or not
            accounts = []
            if user.is_authenticated:
                user_friend_list = FriendsList.objects.get(user=user)
                for account in search_results:
                    accounts.append((account, user_friend_list.check_mutual_friends(account)))
                context['accounts'] = accounts
            else:
                for account in search_results:
                    accounts.append((account, False))
                context['accounts'] = accounts

    return render(request, "accounts/search.html", context)

# Edit Particulars View
def edit_particulars_view(request, *args, **kwargs):
    context = {}

    # check if user is logged in
    if not request.user.is_authenticated:
        return redirect("account:login")
    user_id = kwargs.get("user_id")
    try:
        account = Account.objects.get(pk=user_id)
    except Account.DoesNotExist:
        return HttpResponse("Something went wrong")

    # check if user editing own profile    
    if account.pk != request.user.pk:
        return HttpResponse("This is not your account, you are not allowed to edit this profile!")
    
    if request.method == "POST":
        update_form = EditParticularsForm(request.POST, request.FILES, instance=request.user)
        if update_form.is_valid():
            #delete old profile image so keep the name
            account.profile_image.delete()
            update_form.save()
            return redirect("account:user_view", user_id=account.pk)
        else:
            if(account.date_of_birth == None ):
                date_time_val = account.date_of_birth
            else:
                date_time_val = datetime.datetime.strptime(str(account.date_of_birth), '%Y-%m-%d').strftime('%Y-%m-%d')

            update_form = EditParticularsForm(request.POST, instance=request.user,
                initial={
                    "id": account.pk,
                    "email": account.email,
                    "username": account.username,
                    "full_name": account.full_name,
                    "date_of_birth": date_time_val,
                    "profile_image":account.profile_image,
                    "hide_email": account.hide_email,
                }
            )
            context['update_form'] = update_form

    else:
        if(account.date_of_birth == None):
            date_time_val = account.date_of_birth
        else:
            date_time_val = datetime.datetime.strptime(str(account.date_of_birth), '%Y-%m-%d').strftime('%Y-%m-%d')
        
        update_form = EditParticularsForm(
                    initial={
                        "id": account.pk,
                        "email": account.email,
                        "username": account.username,
                        "full_name": account.full_name,
                        "date_of_birth": date_time_val,
                        "profile_image":account.profile_image,
                        "hide_email": account.hide_email,
                    }
        )

        context['update_form'] = update_form
    return render(request, "accounts/update_particulars.html", context)

def save_temp_profile_image_from_base64String(imageString, user):
    try:
        # all users have a unique temp profile image depending on primary key
        if not os.path.exists(settings.TEMP):
            os.mkdir(settings.TEMP)
        if not os.path.exists(settings.TEMP + "/" + str(user.pk)):
            os.mkdir(settings.TEMP + "/" + str(user.pk))
        url = os.path.join(settings.TEMP + "/" + str(user.pk), TEMP_PROFILE_IMAGE_NAME)
        storage = FileSystemStorage(location=url)
        image = base64.b64decode(imageString)
        with storage.open('', 'wb+') as destination:
            destination.write(image)
            destination.close()
        return url

    except Exception as e:
        if str(e) == "Incorrect padding":
            imageString += "=" * ((4 - len(imageString) % 4) % 4)
            return save_temp_profile_image_from_base64String(imageString, user)
        return None

# called asynchronously through AJAX
def crop_image_view(request, *args, **kwargs):
    payload = {}
    user = request.user
    if request.POST and user.is_authenticated:
        try:

coursework2/accounts/templates/accounts/ajaxScript/cropImage.html
<script type="text/javascript">
    var cropper;
	var imageFile;
	var base64ImageString;
	var cropX;
	var cropY;
	var cropWidth;
	var cropHeight;

	enableImageOverlay()

	function readURL(input){
		if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
            	disableImageOverlay()
            	var image = e.target.result
            	var imageField = document.getElementById('id_profile_image_display')
                imageField.src = image
				cropper = new Cropper(imageField, {
					aspectRatio: 1/1,
					crop(event){
						console.log("CROP")
						console.log("x: " + event.detail.x)
						console.log("y:" + event.detail.y)
						console.log("width: " + event.detail.width)
						console.log("height: " + event.detail.height)
						setImageCropProperties(
							image,
							event.detail.x,
							event.detail.y,
							event.detail.width,
							event.detail.height
						)
					}
				})
            };
            reader.readAsDataURL(input.files[0]);
        }
	}

	function setImageCropProperties(image, x, y, width, height){
		imageFile = image
		cropX = x
		cropY = y
		cropWidth = width
		cropHeight = height
	}

	function isImageSizeValid(image){
		var startIndex = image.indexOf("base64,") + 7
		var base64str = image.substr(startIndex)
		// decode a base64 string
		var decoded = atob(base64str)
		// if bigger 
		if (decoded.length >= "{{DATA_UPLOAD_MAX_MEMORY_SIZE}}"){
			return null
		} 
		return base64str
	}

	function cropImage(image, x, y , width, height){
		base64ImageString = isImageSizeValid(image)
		if(base64ImageString == null){
			alert("Pleae upload an image smaller than 10mb")
			document.getElementById("id_cancel").click()
		} else{
			var requestData = {
				"csrfmiddlewaretoken": "{{csrf_token}}",
				"image": base64ImageString,
				"cropX": cropX,
				"cropY": cropY,
				"cropWidth": cropWidth,
				"cropHeight": cropHeight,
			}
			
			$.ajax({
				type: 'POST',
				dataType: "json",
				url: "{% url 'account:crop_image' user_id=update_form.initial.id %}",
				data: requestData,
				timeout:10000,
				success: function(data){
					if(data.result == "success"){
						window.location.reload()
					} else if(data.result == "error"){
						alert(data.exception)
						window.location.reload()
					}
				},
				error: function(data){
					console.error("ERROR" , data)
				}
			})
		}
	}

	function enableImageOverlay(){
		var text = document.getElementById("id_text")
		text.style.backgroundColor = "#0066ff"
		text.style.color = "white"
		text.style.fontSize = "16px"
		text.style.padding = "16px 32px"
		text.style.cursor = "pointer"

		var profileImg = document.getElementById("id_profile_image")
		profileImg.style.opacity = "1"
		profileImg.style.display = "block"
		profileImg.style.width = "100%"
		profileImg.style.height = "auto"
		profileImg.style.transition = ".5s ease"
		profileImg.style.backfaceVisibility  = "hidden"
		profileImg.style.cursor = "pointer"

		var middleContainer = document.getElementById("id_middle_container")
		middleContainer.style.transition = ".5s ease"
		middleContainer.style.opacity = "0"
		middleContainer.style.position = "absolute"
		middleContainer.style.top = "50%"
		middleContainer.style.left = "50%"
		middleContainer.style.transform = "translate(-50%, -50%)"
		middleContainer.style.textAlign = "center"

		var imageContainer = document.getElementById("id_image_container")
		imageContainer.addEventListener("mouseover", function( event ) { 
			profileImg.style.opacity = "0.3"
			middleContainer.style.opacity = "1"
		})

		imageContainer.addEventListener("mouseout", function( event ) { 
			profileImg.style.opacity = "1"
			middleContainer.style.opacity = "0"
		})

		imageContainer.addEventListener("click", function(event){
			document.getElementById('id_profile_image').click();
		});

		var cropConfirm = document.getElementById("id_image_crop_confirm")
		cropConfirm.classList.remove("d-flex")
		cropConfirm.classList.remove("flex-row")
		cropConfirm.classList.remove("justify-content-between")
		cropConfirm.classList.add("d-none")
		
	}

	function disableImageOverlay(){
		var profileImg = document.getElementById("id_profile_image_display")
		var middleContainer = document.getElementById("id_middle_container")
		var imageContainer = document.getElementById("id_image_container")
		var text = document.getElementById("id_text")

		imageContainer.removeEventListener("mouseover", function( event ) { 
			profileImg.style.opacity = "0.3"
			middleContainer.style.opacity = "1"
		})

		imageContainer.removeEventListener("mouseout", function( event ) { 
			profileImg.style.opacity = "1"
			middleContainer.style.opacity = "0"
		})

		profileImg.style.opacity = "1"
		middleContainer.style.opacity = "0"
		text.style.cursor = "default"
		text.style.opacity = "0"

		document.getElementById('id_image_container').removeEventListener("click", function(event){
			event.preventDefault();
			// do nothing
		});
		document.getElementById('id_profile_image').addEventListener("click", function(event){
			event.preventDefault();
			// do nothing
		});

		var cropConfirm = document.getElementById("id_image_crop_confirm")
		cropConfirm.classList.remove("d-none")
		cropConfirm.classList.add("d-flex")
		cropConfirm.classList.add("flex-row")
		cropConfirm.classList.add("justify-content-between")

		var confirm = document.getElementById("id_confirm")
		confirm.addEventListener("click", function(event){
			cropImage(imageFile, cropX, cropY, cropWidth, cropHeight)
		})

		var cancel = document.getElementById("id_cancel")
		cancel.addEventListener("click", function(event){
			console.log("Reloading window...")
			window.location.reload();
		})
	}
</script>

coursework2/accounts/templates/accounts/ajaxScript/editImage.html
<script type="text/javascript">

	enableImageOverlay()

	// ran when a file is selected
	function readURL(input){
		if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
            	disableImageOverlay()
            	var image = e.target.result
            	var imageField = document.getElementById('id_profile_image_display')
				// change the image display to the image choosen
                imageField.src = image
            };
			// start the function above
            reader.readAsDataURL(input.files[0]);
        }
	}

	function enableImageOverlay(){

		// Image Box
		var profileImg = document.getElementById("id_profile_image")
		profileImg.style.opacity = "1"
		profileImg.style.display = "block"
		profileImg.style.width = "100%"
		profileImg.style.height = "auto"
		profileImg.style.cursor = "pointer"

		// box holding edit text
		var middleContainer = document.getElementById("id_middle_container")
		middleContainer.style.opacity = "0"
		middleContainer.style.position = "absolute"
		middleContainer.style.top = "50%"
		middleContainer.style.left = "50%"
		middleContainer.style.transform = "translate(-50%, -50%)"
		middleContainer.style.textAlign = "center"

		// Edit Text
		var text = document.getElementById("id_text")
		text.style.backgroundColor = "black"
		text.style.color = "white"
		text.style.cursor = "pointer"
		text.style.padding = "12px 28px"

		// parent container holding everything the image and the edit box
		var imageContainer = document.getElementById("id_image_container")
		imageContainer.addEventListener("mouseover", function( event ) { 
			profileImg.style.opacity = "0.3"
			middleContainer.style.opacity = "1"
		})

		imageContainer.addEventListener("mouseout", function( event ) { 
			profileImg.style.opacity = "1"
			middleContainer.style.opacity = "0"
		})

		imageContainer.addEventListener("click", function(event){
			document.getElementById('id_profile_image').click();
		});
		
	}

	function disableImageOverlay(){
		var profileImg = document.getElementById("id_profile_image_display")
		var middleContainer = document.getElementById("id_middle_container")
		var imageContainer = document.getElementById("id_image_container")
		var text = document.getElementById("id_text")

		imageContainer.removeEventListener("mouseover", function( event ) { 
			profileImg.style.opacity = "0.3"
			middleContainer.style.opacity = "1"
		})

		imageContainer.removeEventListener("mouseout", function( event ) { 
			profileImg.style.opacity = "1"
			middleContainer.style.opacity = "0"
		})

		profileImg.style.opacity = "1"
		middleContainer.style.opacity = "0"
		text.style.cursor = "default"
		text.style.opacity = "0"

		document.getElementById('id_image_container').removeEventListener("click", function(event){
			event.preventDefault();
		});
		document.getElementById('id_profile_image').addEventListener("click", function(event){
			event.preventDefault();
		});

	}
</script>