coursework2/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('register/', user_register_view, name="register"),
    path('login/', user_login_view, name="login"),
    path('logout/', user_logout_view, name="logout"),
    path('search/', user_search_view, name="search"),
    path('<user_id>/', user_view, name="user_view"),
    path('<user_id>/edit/', edit_particulars_view, name="edit"),
    path('<user_id>/edit/cropImg', crop_image_view, name="crop_image"),
]

coursework2/base/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home_screen, name='home'),
]

coursework2/chat/urls.py
from django.urls import path
from .views import *

app_name = "chat"

urlpatterns = [
    path('<user_id>/', index_view, name='chat-index'),
    path('chatroom/<str:room_name>/', room_view , name='chat-room'),
]

coursework2/coursework2/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

from accounts.views import *

urlpatterns = [
    path('', include('base.urls'), name="home"),
    path('account/', include('accounts.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('friend/', include('friends.urls', namespace='friend')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('status/', include('status.urls', namespace='status')),
    
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password/password_change.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password/password_change_done.html'), name='password_change_done'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

coursework2/templates/snippets/base_css.html
<style type="text/css">
	body{
		background-color: grey;
		font-weight: 400;
	}
</style>

coursework2/templates/snippets/header.html
{% load static %}

<div class="d-flex flex-column flex-lg-row p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

	<div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
		<h5 class="mr-3 font-weight-normal justify-content-start">
			<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
			{% if request.user.is_authenticated %}
			<a class="p-2 text-dark" href="{% url 'chat:chat-index' user_id=request.user.id %}">Public Chat</a>
			{% endif %}
		</h5>
		<form class="search-bar justify-content-start" onsubmit="return executeQuery()">
			<input type="text" class="form-control" name="q" id="id_query" placeholder="Search Accounts">
		</form>

		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
					<div class="dropdown dropleft show p-2">
						<div class="d-flex flex-row">
							<img class="account-image rounded-circle m-auto d-block" id="id_profile_links" src="{{request.user.profile_image.url}}" alt="default img" width="40" height="40">
							<a class="p-2 text-dark" href="{% url 'account:user_view' user_id=request.user.id %}">Account</a>
							<a class="p-2 text-dark" href="{% url 'account:logout' %}">Logout</a>
						</div>
						
					</div>
				{% else %}
					<a class="p-2 text-dark" href="{% url 'account:login' %}">Login</a>
					<a class="btn btn-outline-primary" href="{% url 'account:register' %}">Register</a>
				{% endif %}	
			</nav>
		</div>
	</div>
</div>

<script type="text/javascript">
	function executeQuery(){
		var query = document.getElementById("id_query").value;
		window.location.replace("{% url 'account:search' %}?q=" + query)
		return false
	}
</script>